name: tmate

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: GitHub-hosted runner to use
        options:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2019
          - windows-2022
          - macos-12
          - macos-13
          - macos-14
          - macos-15
        required: true

jobs:
  tmate:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
