name: tmate

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: GitHub-hosted runner to use
        options:
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-slim
          - xcode-27
          - macos-26
          - macos-26-intel
          - macos-15
          - macos-15-intel
          - macos-14
          - windows-2025
          - windows-2022
          - windows-11-arm
          - windows-11-vs2026-arm
        required: true

jobs:
  tmate:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
