name: tmate

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: GitHub-hosted runner to use
        options:
          - ubuntu-latest
          - windows-latest
          - macos-11
          - macos-12
          - macos-13
          - macos-14
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: mxschmitt/action-tmate@v3
